### ISSUE TITLE
Density of state

### ISSUE THREAD

**Issue by shunsuke-sato** [SALMON-TDDFT/SALMON#122]
- I moved the following comment from the closed PR since the issue tracker would be better for discussion than the closed PR.

@uemoto1 san, thank you for the implementation for PR #109. But, I would like to ask one thing to you.
In the present implementation, the range of the energy for DOS must be specified in input. However, the single particle energies are usually unknown before the calculation. Therefore, it is often impossible to give those values from input.

In the previous implementation, the range of the energy is automatically defined by the highest and lowest single particle energies. So, could you re-implement the automatic range finder, which was deleted by PR #109 ?

I would say that the range should be automatically determined by `default`. It is useful for users, and most applications do that.

**Comment by uemoto1** [comment]
Thank you for comment, @shunsuke-sato san.

In the previous PR, due to the previous implementation of GCEED-side  DoS calculation ("Gaussian smearing" and "fixed electron energy range"), I assume the similar design is easy to implement for the both ARTED and GCEED side.
In the present implementation has one merit; it is possible to control the adequate plot region and sampling density, when the electronic structure and interested electron energy range are already clear.
On the other hand, as you mentioned,  sometimes it is often difficult to give adequate values as input variables.
An idea I propose is providing an additional variable in inputfile to switch the automatic range specification. (set default as enabling)

If someone can have time enough, please add this routine both for ARTED and GCEED section.

**Comment by shunsuke-sato** [comment]
@uemoto1 san, thank you for your quick response!
I knew the merit for controlling the plot range. However, if the auto-range function does not exist, it would be quite inconvenient for users because SALMON requires the same DFT calculation twice to get DOS. One is to define the energy range, and the other is to compute DOS. Thus, I proposed to employ the auto-range function as default. Of cause, the range can be controlled optionally.

Because you deleted the auto-range function, I first asked you to fix it. But, if you do not do that, I will re-implement it later.

**Comment by uemoto1** [comment]
Okay, I consider a simpler implementation method for the above case.

In this idea, the default value of `out_dos_start` and `out_dos_end` are set to be large negative/positive number which does not appear in the electron eigenenergy.
At the stage of DoS calculation, clip the `out_dos_start`/`out_dos_end` to the lower/upper bound of the calculated eigenenergies.

In this implementation, if the `out_dos_(start|end)` is not specified,  the upper/lower limit of eigen energies are automatically assigned. And in this case, it is not necessary to add one another input variables to switch the automatic detection.

If no one wants to assign to this modification, I will assign to it.

**Comment by shunsuke-sato** [comment]
@uemoto1 san, thank you for your understanding.
I personally think that a person who breaks/deletes a function should have responsibility to fix/recover it. This would be only a solution for healthy development.
Otherwise, someone has to repeat the same implementation for several times...

**Comment by shunsuke-sato** [comment]
The problem has been fixed. Then, I close the issue.
