### ISSUE TITLE
Smoothing of ionic charge

### ISSUE THREAD

**Issue by shunsuke-sato** [SALMON-TDDFT/SALMON#41]
In the ARTED part, long-range parts of local pseudopotentials are constructed by the Coulomb potential of a point charge, basically, in preparation/prep_ps.f90;
`4*Pi*sin(G2sq*r)/(G2sq)*(r*vloc_av+Zps(ik))*(rad(i,ik)-rad(i-1,ik))`

This treatment seems to make a grid-convergence rather slow in some cases.
Probably, we need to employ "pseudised" charge distribution instead of the point charge one.

**Comment by ayamada224** [comment]
I tested smoothing of ionic charge instead of using the above point-charge Coulomb potential. I confirmed this does not make grid-convergence slow nor make force values inaccurate/unstable. So, at least in my tests, this part is not problem. 
(The slow grid-convergence was resolved recently by introducing gradient of wave function in force calculation instead of gradient of potential.)
